spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vueblog2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 410520
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
  error:
    whitelabel:
      enabled: true

  mybatis:
    config-location:
      classpath: /mybatis-config.xml